# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(upload_to='books/thumbnails')),
                ('file', models.FileField(upload_to='books/files')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('publish_time', models.DateTimeField(null=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('status', models.CharField(choices=[('d', '\u8349\u7a3f'), ('p', '\u5df2\u53d1\u5e03')], default='d', max_length=1, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='\u540d\u79f0')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u4e66\u7c4d\u5206\u7c7b',
                'verbose_name_plural': '\u4e66\u7c4d\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category', verbose_name='\u6240\u5c5e\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='books.Tag', verbose_name='\u6807\u7b7e\u96c6\u5408'),
        ),
    ]
