# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['update_time'], 'verbose_name': '\u4e66\u7c4d', 'verbose_name_plural': '\u4e66\u7c4d'},
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u8005'),
            preserve_default=False,
        ),
    ]
