# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 02:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='\u6807\u9898')),
                ('link', models.CharField(default='', help_text="Cool URIs don't change", max_length=150, verbose_name='\u94fe\u63a5')),
                ('cover', models.URLField(blank=True, default='', verbose_name='\u5c01\u9762')),
                ('snippet', models.CharField(default='', max_length=500, verbose_name='\u6458\u8981')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('publish_time', models.DateTimeField(null=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('status', models.CharField(choices=[('d', '\u8349\u7a3f'), ('p', '\u5df2\u53d1\u5e03')], default='d', max_length=1, verbose_name='\u72b6\u6001')),
                ('is_public', models.BooleanField(default=True, verbose_name='\u516c\u5f00')),
                ('is_top', models.BooleanField(default=False, verbose_name='\u7f6e\u9876')),
                ('access_count', models.IntegerField(default=1, editable=False, verbose_name='\u6d4f\u89c8\u91cf')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='\u540d\u79f0')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u6587\u7ae0\u5206\u7c7b',
                'verbose_name_plural': '\u6587\u7ae0\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u6240\u5c5e\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='\u6807\u7b7e', null=True, to='blog.Tag', verbose_name='\u6807\u7b7e\u96c6\u5408'),
        ),
    ]
